// Curated exercise catalog — minimal seed covering the 3 equipment tiers.
//
// equipment tag convention (mirrors user_profiles.equipment enum):
//   ['home']     = bodyweight, works everywhere
//   ['home_eq']  = needs dumbbells/resistance bands — works at home_eq or gym
//   ['gym']      = requires barbells / cables / machines — gym only
//
// Rep ranges and rest defaults are reasonable starting points.
// ⚠️ PENDING OWNER CONFIRMATION via topics/progressive-overload.md before
//    adjusting progression rules or deload schedule.

import type { NewExercise } from '@/lib/types/db/workouts';

type SeedExercise = Omit<NewExercise, 'id' | 'createdAt' | 'updatedAt' | 'source'>;

export const EXERCISE_SEEDS: SeedExercise[] = [
  // ── GYM ───────────────────────────────────────────────────────────────────
  {
    semanticId: 'barbell_squat',
    nameTh: 'สควอตบาร์เบล',
    nameEn: 'Barbell Squat',
    muscleGroups: ['quads', 'glutes', 'hamstrings', 'core'],
    equipment: ['gym'],
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRestSec: 90,
    tipTh: 'เข่าชี้ปลายเท้า หลังตรง ลงจนขาขนานพื้น',
    formCuesTh: ['เข่าชี้ออกด้านข้าง', 'หน้าอกชูขึ้น', 'ส้นเท้าติดพื้น'],
    videoUrl: null,
  },
  {
    semanticId: 'barbell_bench_press',
    nameTh: 'เบนช์เพรสบาร์เบล',
    nameEn: 'Barbell Bench Press',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: ['gym'],
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRestSec: 90,
    tipTh: 'ไหล่ลงติดม้านั่ง หายใจออกตอนดัน',
    formCuesTh: ['จับกว้างกว่าไหล่', 'ลงช้าๆ 2 วินาที', 'ข้อศอกพับ 45 องศา'],
    videoUrl: null,
  },
  {
    semanticId: 'barbell_deadlift',
    nameTh: 'เดดลิฟท์บาร์เบล',
    nameEn: 'Barbell Deadlift',
    muscleGroups: ['back', 'glutes', 'hamstrings', 'core'],
    equipment: ['gym'],
    defaultSets: 3,
    defaultReps: '6-8',
    defaultRestSec: 120,
    tipTh: 'หลังตรง สะโพกเป็นตัวขับเคลื่อน',
    formCuesTh: ['แกนชิดขา', 'กดส้นเท้าลงพื้น', 'ล็อคสะโพกบนสุด'],
    videoUrl: null,
  },
  {
    semanticId: 'barbell_row',
    nameTh: 'โรว์บาร์เบล',
    nameEn: 'Barbell Row',
    muscleGroups: ['back', 'biceps', 'core'],
    equipment: ['gym'],
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRestSec: 90,
    tipTh: 'ลำตัวขนานพื้น ดึงแกนเข้าสะดือ',
    formCuesTh: ['หลังตรง', 'กดสะบักเข้าหากัน', 'ข้อศอกชิดลำตัว'],
    videoUrl: null,
  },
  {
    semanticId: 'overhead_press',
    nameTh: 'โอเวอร์เฮดเพรส',
    nameEn: 'Overhead Press',
    muscleGroups: ['shoulders', 'triceps', 'core'],
    equipment: ['gym'],
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRestSec: 90,
    tipTh: 'แกนเริ่มที่หน้าไหล่ ดันตรงขึ้นเหนือหัว',
    formCuesTh: ['ล็อคคอร์', 'ไม่แอ่นหลัง', 'ข้อศอกล็อคบนสุด'],
    videoUrl: null,
  },
  {
    semanticId: 'lat_pulldown',
    nameTh: 'แลท พูลดาวน์',
    nameEn: 'Lat Pulldown',
    muscleGroups: ['back', 'biceps'],
    equipment: ['gym'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 75,
    tipTh: 'ดึงลงที่หน้าอก ไม่ใช่ด้านหลัง',
    formCuesTh: ['แอ่นหน้าอกขึ้นเล็กน้อย', 'ข้อศอกชี้ลง', 'กดสะบักเข้าหากัน'],
    videoUrl: null,
  },
  {
    semanticId: 'leg_press',
    nameTh: 'เลก เพรส',
    nameEn: 'Leg Press',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['gym'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 90,
    tipTh: 'เท้าห่างไหล่ หัวเข่าอย่าล็อค',
    formCuesTh: ['ลงจนขา 90 องศา', 'ไม่ให้หัวเข่าแตะหน้าอก', 'ดันส้นเท้า'],
    videoUrl: null,
  },

  // ── HOME_EQ (ดัมเบล / แรงต้าน) ──────────────────────────────────────────
  {
    semanticId: 'dumbbell_squat',
    nameTh: 'สควอตดัมเบล',
    nameEn: 'Dumbbell Squat',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['home_eq'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 75,
    tipTh: 'ถือดัมเบลสองมือที่ไหล่หรือข้างลำตัว',
    formCuesTh: ['เข่าชี้ปลายเท้า', 'หลังตรง', 'ลงช้าๆ 2 วินาที'],
    videoUrl: null,
  },
  {
    semanticId: 'dumbbell_press',
    nameTh: 'ดัมเบลเพรส',
    nameEn: 'Dumbbell Press',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: ['home_eq'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 75,
    tipTh: 'นอนราบหรือนั่งตั้งตรง ดันดัมเบลขึ้นตรง',
    formCuesTh: ['ไหล่ลง', 'ข้อศอกไม่ล็อคบนสุด', 'ลงช้าๆ'],
    videoUrl: null,
  },
  {
    semanticId: 'dumbbell_row',
    nameTh: 'ดัมเบลโรว์',
    nameEn: 'Dumbbell Row',
    muscleGroups: ['back', 'biceps'],
    equipment: ['home_eq'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 75,
    tipTh: 'วางมือและเข่าฝั่งตรงข้ามบนม้านั่งหรือเก้าอี้',
    formCuesTh: ['หลังขนานพื้น', 'ดึงข้อศอกขึ้น', 'กดสะบัก'],
    videoUrl: null,
  },
  {
    semanticId: 'dumbbell_shoulder_press',
    nameTh: 'ดัมเบลเพรสไหล่',
    nameEn: 'Dumbbell Shoulder Press',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: ['home_eq'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 75,
    tipTh: 'นั่งตัวตรง ดันขึ้นเหนือหัว',
    formCuesTh: ['ไม่แอ่นหลัง', 'ข้อศอกไม่ล็อคบนสุด', 'ลงจนแขนขนานพื้น'],
    videoUrl: null,
  },
  {
    semanticId: 'romanian_deadlift_db',
    nameTh: 'โรมาเนียน เดดลิฟท์ ดัมเบล',
    nameEn: 'Romanian Deadlift (Dumbbell)',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: ['home_eq'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 75,
    tipTh: 'โน้มตัวลงโดยสะโพกถอยหลัง ดัมเบลชิดขา',
    formCuesTh: ['หลังตรง', 'รู้สึกตึงหลังขา', 'ล็อคสะโพกขึ้น'],
    videoUrl: null,
  },
  {
    semanticId: 'dumbbell_lunge',
    nameTh: 'ลันจ์ดัมเบล',
    nameEn: 'Dumbbell Lunge',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['home_eq'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRestSec: 60,
    tipTh: 'ก้าวยาว เข่าหน้าไม่เลยปลายเท้า',
    formCuesTh: ['ลำตัวตั้งตรง', 'เข่าหลังเกือบแตะพื้น', 'ดันส้นเท้ากลับ'],
    videoUrl: null,
  },

  // ── HOME (น้ำหนักตัว) ─────────────────────────────────────────────────────
  {
    semanticId: 'pushup',
    nameTh: 'วิดพื้น',
    nameEn: 'Push-Up',
    muscleGroups: ['chest', 'triceps', 'shoulders', 'core'],
    equipment: ['home'],
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRestSec: 60,
    tipTh: 'ลำตัวเป็นเส้นตรงตลอด ข้อศอกพับ 45 องศา',
    formCuesTh: ['ล็อคคอร์', 'คางเกือบแตะพื้น', 'ดันตัวขึ้นเต็มช่วง'],
    videoUrl: null,
  },
  {
    semanticId: 'bodyweight_squat',
    nameTh: 'สควอตน้ำหนักตัว',
    nameEn: 'Bodyweight Squat',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['home'],
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRestSec: 45,
    tipTh: 'แขนยื่นหน้าเพื่อทรงตัว ลงจนขาขนานพื้น',
    formCuesTh: ['เข่าชี้ปลายเท้า', 'หลังตรง', 'น้ำหนักที่ส้นเท้า'],
    videoUrl: null,
  },
  {
    semanticId: 'plank',
    nameTh: 'แพลงค์',
    nameEn: 'Plank',
    muscleGroups: ['core', 'shoulders'],
    equipment: ['home'],
    defaultSets: 3,
    defaultReps: '30-45',
    defaultRestSec: 45,
    tipTh: 'ค้างไว้ 30-45 วินาที ลำตัวตรง',
    formCuesTh: ['สะโพกไม่ยกสูง', 'ไม่แอ่นหลัง', 'กดข้อศอกลงพื้น'],
    videoUrl: null,
  },
  {
    semanticId: 'lunge',
    nameTh: 'ลันจ์',
    nameEn: 'Lunge',
    muscleGroups: ['quads', 'glutes'],
    equipment: ['home'],
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRestSec: 45,
    tipTh: 'ก้าวยาว เข่าหลังเกือบแตะพื้น',
    formCuesTh: ['ลำตัวตรง', 'เข่าหน้าไม่เลยนิ้วเท้า', 'ก้าวสลับซ้าย-ขวา'],
    videoUrl: null,
  },
  {
    semanticId: 'glute_bridge',
    nameTh: 'กลูท บริดจ์',
    nameEn: 'Glute Bridge',
    muscleGroups: ['glutes', 'hamstrings', 'core'],
    equipment: ['home'],
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRestSec: 45,
    tipTh: 'นอนหงาย งอเข่า ยกสะโพกขึ้นค้าง 2 วินาที',
    formCuesTh: ['บีบก้น', 'หลังตรง', 'เท้าราบพื้น'],
    videoUrl: null,
  },
  {
    semanticId: 'mountain_climber',
    nameTh: 'เมาน์เทน ไคลมเบอร์',
    nameEn: 'Mountain Climber',
    muscleGroups: ['core', 'shoulders', 'quads'],
    equipment: ['home'],
    defaultSets: 3,
    defaultReps: '20-30',
    defaultRestSec: 45,
    tipTh: 'สลับเข่าเข้าหาหน้าอกเร็วๆ ลำตัวตรง',
    formCuesTh: ['ล็อคแขน', 'สะโพกไม่สูง', 'หายใจสม่ำเสมอ'],
    videoUrl: null,
  },
];
